### ISSUE TITLE
BOOST_USE_VALGRIND?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/coroutine2#11]
The Coroutine2 docs state (doc/stack.qbk)

>Running programs that switch stacks under valgrind causes problems. Property (b2 command-line) `valgrind=on` let valgrind treat the memory regions as stack space which suppresses the errors.

However, I searched through the source code and I cannot find the text "valgrind" anywhere. Is this still a supported feature?

Thanks

**Comment by olk** [comment]
it is in boost.context (stack switching; valgrind has to keep track of stack switches)
note that you have to apply BOOST_USE_VALGRIND too

**Comment by vinniefalco** [comment]
Excellent, I found the code and I can see the feature rule in the jamfile - thanks!

**Comment by olk** [comment]
hmm - please keep in mind that boost.coroutine is deprecated.
boost.coroutine dublicates code from boost.context (see include/boost/coroutine/standard_stack_allocator.hpp).
but it should work too :)

**Comment by vinniefalco** [comment]
I don't use Boost.Coroutine directly, I use Boost.Asio. I hope that the deprecated Boost.Coroutine problem is resolved. To be honest, it was a bit of a mess, I think it is bad form to deprecate a Boost library that is currently in use by another Boost library, without coordinating with the author of the other library.

**Comment by olk** [comment]
I've already posted a pull request (https://github.com/boostorg/asio/pull/52) that enables boost.coroutine2 in boost.asio - unfortunately not merged yet.

**Comment by vinniefalco** [comment]
Ah, wonderful! The author informed me that there will be an update to Asio before 1.66.0, it was pending a freeze on Net-TS. I'm sure it will get merged then (I'll keep an eye on it).
