### ISSUE TITLE
Pull coroutine does not rethrow an exception if it is thrown on the first entry

### ISSUE THREAD

**Issue by ztlpn** [boostorg/coroutine2#13]
Here is the test program: https://gist.github.com/ztlpn/77a0ff1c0537f5ce8f81227c511b028b

I expect that the exception will be rethrown and the program will print `Exception: Error`, but it prints nothing. If the `yield()` statement is uncommented, everything is as expected.

I am testing with coroutine2 library from boost 1.64.0.

**Comment by olk** [comment]
ty, rethrow_exception() was missing in the ctor of pull-coroutine ... fixed in branch develop (unfotunately too late for boost-1.65).

**Comment by ztlpn** [comment]
Ok, thanks for the quick fix!
