### ISSUE TITLE
Crash while stack unwinding, if compiled by Visual Studio 2015 Upd.3 without / GL flag

### ISSUE THREAD

**Issue by DrKelwin** [boostorg/coroutine2#14]
[BoostCoroTest.zip](https://github.com/boostorg/coroutine2/files/1303646/BoostCoroTest.zip)
I've attached configured sample which crashes (*.sln and source file). Can be reproduced if this solution compiled on Release & x86 configuration. /O2 and /Ob2 are enabled, all other options are disabled. If /GL (in VS it calls: "Whole Program Optimization") is enabled all works fine.

I used Boost.Coroutine2 from boost 1.65.1.

**Comment by olk** [comment]
does it happen with context-impl=winfib (b2 command line property; uses Windows Fibers instead of assembler implementation) too?

**Comment by DrKelwin** [comment]
Great! Thanks! context-impl=winfib helped. But it works only if link=static. If I changed to link=shared then I see errors like 

"boost/context/continuation_winfib.hpp(66): error C2492: 'boost::context::detail::activation_record::current_rec': data with thread storage duration may not have dll interface".

Do you have any ideas how can I fix it? Maybe some preprocessor definitions will help or some other tricks...

**Comment by olk** [comment]
What tells the compiler if the you add BOOST_CONTEXT_DECL at the front (line 66)?

**Comment by olk** [comment]
From the error C2492 reference: "The address of the thread variable is not known until run time, so it cannot be linked to a DLL import or export."

**Comment by olk** [comment]
I've updated boost.context (branch develop). Could you check if the error regarding to the DLL interface has vanished, please?

**Comment by olk** [comment]
no, response - so closed
