### ISSUE TITLE
Some guidance on why to use coroutine2 instead of coroutine

### ISSUE THREAD

**Issue by jrversteegh** [boostorg/coroutine2#18]
Could you please add some guidance on how to select between coroutine and coroutine2 in README or manual? Is coroutine deprecated? No reference is made from either library to the other. Whether they are successors, alternatives... Some clarification would really help.

**Comment by olk** [comment]
I've added some words ... I hope it's sufficient. thx

**Comment by jrversteegh** [comment]
thank you! also for a great library.
