### ISSUE TITLE
Simple coroutine crash

### ISSUE THREAD

**Issue by JuglansN** [boostorg/coroutine2#19]
Following program crashes when compiled with Visual Studio 2015 Update 3, win32, release build. But does not in debug build or if cout is uncommented. Boost version 1.66
```
int main() {
    typedef boost::coroutines2::coroutine<void> coro_t;
    coro_t::pull_type coro([&](coro_t::push_type& yield) {
        //std::cout << "111";
    });
    return 0;
}
```

**Comment by olk** [comment]
I don't use Windows, could you try your example with a larger stack size + uncommented cout?
`coro_t::pull_type coro(fixedsize_stack(1024*1024), [&](coro_t::push_type& yield) {`

**Comment by JuglansN** [comment]
fixedsize_stack(1024*1024) doesn't change behaviour.
I've also tried to run it in VS2017:
```
(boost\context\continuation_fcontext.hpp)

transfer_t context_unwind( transfer_t t) {
    throw forced_unwind( t.fctx);  <---- Unhandled exception at 0x761633AB (ucrtbase.dll) in CoroTest.exe: Fatal program exit requested.
    return { nullptr, nullptr };
}
```

**Comment by olk** [comment]
I can't reproduce your problem. I've used msvc-14.1 (VS 2017) and built the test code in directory coroutine2/example.

**Comment by JuglansN** [comment]
Every example from coroutine2/example work fine, but my test code does not. Is empty coroutine prohibited? Project attached, I build it in release/x86 configuration.
[CoroTest.zip](https://github.com/boostorg/coroutine2/files/1710018/CoroTest.zip)

**Comment by olk** [comment]
I'm not familair with MSVC/Windows but I guess your problem is related to incompatible compiler flags used to compile the boost libraries and the settings in you MSVC project.

**Comment by JuglansN** [comment]
Flags used to compile boost do not affect my issue. Problem goes away if I turn off global program optimization (/GL) or change /EHsc (default, tells the compiler to assume that functions declared as extern "C" never throw a C++ exception) to /EHs (tells the compiler to assume that functions declared as extern "C" may throw an exception).  Does boost throw exceptions from extern "C" functions?

**Comment by olk** [comment]
yes, an exception might be thrown by ontop_fcontext() (declared as extern 'C') is used in the dtor if stack was not destructed.

**Comment by JuglansN** [comment]
Ok, thank you for help!

**Comment by olk** [comment]
thank you too

**Comment by devshgraphicsprogramming** [comment]
@olk any chance of using coroutine2/context with global program optimization under MSVC?

**Comment by olk** [comment]
@devshgraphicsprogramming : I don't know - becaue I don't use Windows

**Comment by devshgraphicsprogramming** [comment]
is there a particular reason `\GL` must be disabled?

**Comment by JuglansN** [comment]
Actually,  /EHs should be enough.
