### ISSUE TITLE
Undefined behaviour documentation

### ISSUE THREAD

**Issue by hamparawa** [boostorg/coroutine2#22]
Hi,
The documentation states that,

> Calling coroutine<>::push_type::operator() and coroutine<>::pull_type::operator() from inside the same coroutine results in undefined behaviour. 

and provides the following example,

```
boost::coroutines2::coroutine<void>::push_type coro(
    [&](boost::coroutines2::coroutine<void>::pull_type& yield){
        yield();
});
coro();
```

Shouldn't this be something like this?

```
boost::coroutines2::coroutine<void>::push_type coro(
    [&](boost::coroutines2::coroutine<void>::pull_type& yield){
        coro();
});
coro();
```

**Comment by hamparawa** [comment]
#21

**Comment by olk** [comment]
right, ty
