### ISSUE TITLE
test_coroutine_native run where they are not supported

### ISSUE THREAD

**Issue by Kojoley** [boostorg/coroutine2#29]
The test requirements does not include requirements of context fibers. On 32bit MinGW `thread_local` is banned in boost because `__cxa_thread_atexit` crashes with them, resulting in not building fibers (the `cxx11_thread_local` requirement), but the test does not have that requirement and fails at linking. It either should be fixed in context by providing pseudo fiber library that will have usage requirements or just mirroring fiber build requirements on tests here.

**Comment by olk** [comment]
could you provide a patch please

**Comment by Kojoley** [comment]
I do not have a patch, sorry
