### ISSUE TITLE
Boost.Coroutine2 documentation reflects Boost.Coroutine interface

### ISSUE THREAD

**Issue by ipapadop** [boostorg/coroutine2#3]
It appears that somehow the interface of Boost.Coroutine is reflected in the Boost.Coroutine2 documentation.

Examples:
http://www.boost.org/doc/libs/1_62_0/libs/coroutine2/doc/html/coroutine2/coroutine/asymmetric/push_coro.html
http://www.boost.org/doc/libs/1_62_0/libs/coroutine2/doc/html/coroutine2/coroutine/asymmetric/pull_coro.html

**Comment by olk** [comment]
fixed, thx
