### ISSUE TITLE
Crash on cygwin x64

### ISSUE THREAD

**Issue by viric** [boostorg/coroutine2#34]
Coroutine2 does not seem to work under cygwin.

This code:
https://github.com/NixOS/nix/blob/2.3.9/src/libutil/serialise.cc#L188
crashes right away with a quite misterious backtrace on Access Violation.

I don't know whether this is a problem of coroutine2 or context. https://github.com/boostorg/context

**Comment by olk** [comment]
unfortunately cygwin is not supported

**Comment by viric** [comment]
What if we provide a patch that would make it work? Or it will be refused?

**Comment by olk** [comment]
you are welcome to provide a patch/pull-request

**Comment by viric** [comment]
Hmmm I found a workaround. This made it work:
https://www.boost.org/doc/libs/1_75_0/libs/context/doc/html/context/architectures.html

" If the architecture is not supported but the platform provides ucontext_t, Boost.Context should be compiled with BOOST_USE_UCONTEXT and b2 property context-impl=ucontext. "

Could we get in a patch that, on cygwin, chooses that configuration? Or that would be the first ever about cygwin?
