### ISSUE TITLE
How coroutine2 communicates between coroutines

### ISSUE THREAD

**Issue by zchGithub123** [boostorg/coroutine2#40]
How coroutine2 communicates between coroutines?

**Comment by olk** [comment]
I don't understand your question. A coroutine does not communicate with other coroutines.

**Comment by unicomp21** [comment]
I think the question is about something similar to a channel in golang.  For example a c++ queue which support co_await on the enqueue/dequeue.  asio supports co_await on tcp socket read/write, might be worth a visit.  @zchGithub123

**Comment by unicomp21** [comment]
https://github.com/boostorg/beast

**Comment by unicomp21** [comment]
redpanda also leverage co_await heavily, and has many examples

https://github.com/vectorizedio/redpanda/search?q=co_await

**Comment by olk** [comment]
co:await is C++20 coroutine specific ... has nothing to do with boost.coroutine2

> I think the question is about something similar to a channel in golang. For example a c++ queue which support co_await on the enqueue/dequeue. asio supports co_await on tcp socket read/write, might be worth a visit. @zchGithub123

co:await is C++20 coroutine specific ... has nothing to do with boost.coroutine2

**Comment by olk** [comment]
If you ask how to transfer data between two coroutines than you can simply use any type of container etc.
coro1 pushes value to a container and coro2 pops values from the container - both coroutines need access to the same container of course.

**Comment by unicomp21** [comment]
Right, so is there a similar channel/queue concept for coroutine2?

**Comment by olk** [comment]
no, because it's out of the scope of boost.coroutine2.
boost.fiber provides channels... but it utilizes fibers.

**Comment by zchGithub123** [comment]
@olk @unicomp21 thanks!
