### ISSUE TITLE
reenter?

### ISSUE THREAD

**Issue by Memoryss** [boostorg/coroutine2#5]
when i create push_type pointer. after doing something, I need to stop this coroutine , i delete this push_type pointer . after this, why this coroutine reenter funtion and resume?

**Comment by olk** [comment]
Sorry, I don't really understand your point.
First you should never call 'delete this' - especially when 'this' was created by the framework (boost.coroutine2). Second, if the coroutine was not finished, but its instance goes out of scope it renters the coroutine and cleans-up the stack (destructing all objects, deallocating the stack).

**Comment by Memoryss** [comment]
If I can't call 'delete this', how do I interrupt coroutine2?

**Comment by olk** [comment]
What do you mean with interrupting a coroutine? A coroutine can be resumed or suspended - interruption makes more sense in the context of threads/tasks. 
delete this men's destroying the object.

**Comment by Memoryss** [comment]
In the previous 1.60 Coroutine, I use Coroutine::call_type::swap() to restart this Coroutine. But now, I don't know how to restart this Coroutine2.

**Comment by olk** [comment]
I you do swap() on a temporary instance the coroutine gets not resumed, its entered to be destructed (stack unwound ...).
coroutines are resumed by calling operator()().

**Comment by Memoryss** [comment]
`void CoroutineJob::start()
 {
    Coroutine::call_type tmp(m_f);
    m_rt.swap(tmp);
    resume();
}

void CoroutineJob::restart() 
{
    unwind();
    start();
}

void CoroutineJob::resume() 
{
    if (m_rt)
    {
        m_rt(None());
    }
}

void CoroutineJob::unwind() 
{
    Coroutine::call_type tmp;
    m_rt.swap(tmp);
}
`
Above is the Coroutine code, I want to migrate to Coroutine2. But I don't know how to write the ‘unwind() ’

**Comment by olk** [comment]
You use symmetric coroutines - but symmetric coroutines are not supported by boost.coroutine2. That's because the API was misleading and conceptually incorrect. You should use execution_context from boost.context (provides symmetric context switching) or boost.fiber instead.

**Comment by Memoryss** [comment]
All right. Thank you for your answers.
